apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31322   # optional: you can let Kubernetes assign automatically
